#!/bin/bash
#
# rayfixslm v0.2 ray@ebh

function help {
 echo
 echo "$0"
 echo "Automatically convert SLM RAM resources to simplified UBC and is considered safe to run on running containers"
 echo 
 echo "Syntax:"
 echo " $0 <CTID> "
 echo
 echo Ver 0.2 ray@ebh 4/16/2013
 echo 
}

# Tests: arg count must = 1 , conf file exist, mk backup dir if needed
if [ $# != 1 ]; then echo "Error: Wrong number of arguments specified"; help; exit 11; fi
if ! [ -e /etc/vz/conf/${1}.conf ]; then echo -e "$1 \n Error: The specified CTID does not exist on this system"; help; exit 1; fi
[ -e /etc/vz/conf/rayslmfix ] || mkdir -v /etc/vz/conf/rayslmfix

# Detect RAM limit and convert physpages.b to MB
newram=`echo "$(vzlist $1 -Ho physpages.b) / 256"| bc`

# make a non-clobbering backup of conf file
echo "Making backup of conf file.  created: /etc/vz/conf/rayslmfix/${1}_rayslmfix_`date +%F`"
rsync -L --ignore-existing /etc/vz/conf/${1}.conf /etc/vz/conf/rayslmfix/${1}_rayslmfix_`date +%F`
##cp -nv /etc/vz/conf/${1}.conf /etc/vz/conf/rayslmfix/${1}_rayslmfix_`date +%F`  # -n isn't supported on centos 5.x

echo "Converting vps${1} to UBC limits with ${newram}M RAM"
for each in {kmemsize,lockedpages,privvmpages,shmpages,numproc,physpages,vmguarpages,oomguarpages,numtcpsock,numflock,numpty,numsiginfo,tcpsndbuf,tcprcvbuf,othersockbuf,dgramrcvbuf,numothersock,dcachesize,numfile,numiptent,swappages,slmmode,slmmemorylimit}; do vzctl unset ${1} --${each} --save; done
vzctl set ${1} --ram ${newram}M --swap 0 --save

